Backup/MvcLearningApp/Controllers/ClientsListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLearningApp.Repositories;
using MvcLearningApp.Models;

namespace MvcLearningApp.Controllers
{
    public class ClientsListController : Controller
    {
        private ClientsRepository clientRepo;
        public ClientsListController()
        {
            clientRepo = new ClientsRepository();
        }
        //
        // GET: /ClientsList/

        public ActionResult IndexListClients()
        {
            return View(new ClientIndexView() { List = clientRepo.GetAllClients() });
        }
    }
}

Backup/MvcLearningApp/Controllers/ClientsManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcLearningApp.Repositories;
using MvcLearningApp.Helper;
using System.Threading;
using MvcLearningApp.Models;

namespace MvcLearningApp.Controllers
{
    [Authorize]
    [CheckSessionValid]
    public class ClientsManagerController : Controller
    {

        private ClientsRepository _clientRepo;
        public ClientsManagerController()
        {
            _clientRepo = new ClientsRepository();
        }

        //
        // GET: /ClientsManager/

        public ActionResult Index()
        {
            return View();
        }

        //[OutputCache(Duration=3000)]
        public JsonResult GetListAsync(int? page, string words)
        {
            //Thread.Sleep(3000);
            string msg = "Afisare clienti";
            bool ok = true;
            var model = new GridViewModel<ClientView>();
            try
            {
                model = _clientRepo.Compute(page, words, Convert.ToInt32(Session["Id_User"]));
                if (model.Items == null)
                {
                    msg = "List empty for this user";
                    ok = false;
                }
            }
            catch (Exception ex)
            {
                msg = ex.Message;
                ok = false;
            }
            return Json(new { 
                Success=ok,
                Message=msg,
                Html = ok ? this.RenderPartialView("_ClientsManagerList", model) : ""
            });
        }

        public JsonResult CreateAsync(ClientView model)
        {

            string msg = "Salvare Client";
            bool ok = true;
            var res = new ClientView();
            try
            {
                //foreach (string inputStringFile in Request.Files)
                //{
                //    HttpPostedFileBase avatar = Request.Files[inputStringFile];
                    //throw new Exception("Testing...");
                    if (!_clientRepo.IsUniqueClient(model.Email))
                    {
                        ok = false;
                        ModelState.AddModelError("Email", "Email in use");
                    }
                    else
                    {
                        res = _clientRepo.AddClient(model, Convert.ToInt32(Session["Id_User"]), null);

                    }
                //}
            }
            catch (Exception ex)
            {
                ok = false;
                msg = ex.Message;
            }

            return Json(new
            {
                Html = ok ? this.RenderPartialView("_NewRow", res) : "",
                Form = ok ? "" : this.RenderPartialView("_Create", model),
                Success = ok,
                Message = msg
            });
        }

        public JsonResult SaveClient(int id, string name, DateTime date, string mail)
        {
            var res = new ClientView();
            bool ok = true;
            var msg = "";

            try
            {
                var model = new ClientView();
                model.Id = id;
                model.Name = name;
                model.Email = mail;
                model.Date = date;
                res = _clientRepo.PostEditClient(model);
            }
            catch (Exception ex)
            {
                ok = false;
                msg = ex.Message;
            }
            return Json(new
            {
                Html = ok ? this.RenderPartialView("_NewRow", res) : "",
                Success = ok,
                Message = msg
            });
        }

        [HttpGet]
        public JsonResult GetEditAsync(int id)
        {
            string mesaj = string.Empty;
            var clientToEdit = new ClientView();
            try
            {
                clientToEdit = _clientRepo.GetEditClient(id);
            }
            catch (Exception ex)
            {
                mesaj = ex.Message;
            }
            return Json(new
            {
                Message = mesaj,
                Html = this.RenderPartialView("Edit", clientToEdit)
            });
        }

        [HttpPost]
        public JsonResult DeleteAsync(int id)
        {
            //Thread.Sleep(2000);
            string msg = "Delete Client";
            bool ok = true;
            if (_clientRepo.DeleteClient(id))
            {
                ok = true;
            }
            else
            {
                ok = false;
                msg = "Stergerea clientului a esuat, va rugam mai incercati";
            }

            return Json(new
            {
                Success = ok,
                Message = msg
            });
        }
    }
}

Backup/MvcLearningApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <link href="@Url.Content("~/Content/themes/base/jquery.ui.all.css")" rel="stylesheet" type="text/css" />
        <script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/jquery-ui-1.8.17.min.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/modernizr-2.0.6-development-only.js")" type="text/javascript"></script>
        <script src="@Url.Content("~/Scripts/AjaxLogin.js")" type="text/javascript"></script>
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here.", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LogOnPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                        @if(Session["IsAdmin"] != null && Convert.ToBoolean(Session["IsAdmin"]))
                            {
                                <li>@Html.ActionLink("Users", "Index", "Users", new { area = "Admin" }, new { })</li>
                            }
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Clients List", "IndexListClients", "ClientsList")</li>
                            <li>@Html.ActionLink("Management", "Index", "ClientsManager")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://facebook.com" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

Backup/MvcLearningApp/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <p>
        Hello, @Html.ActionLink(User.Identity.Name, "ChangePassword", "Account", new { area = "" }, new { @class = "username" })!
        @Html.ActionLink("Log Off", "LogOff", "Account", new { area = "" }, new { })
    </p>
} else {
    <ul>
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: new {area=""}, htmlAttributes: new { id = "registerLink", data_dialog_title = "Registration" })</li>
        <li>@Html.ActionLink("Log on", "LogOn", "Account", routeValues: new { area = "" }, htmlAttributes: new { id = "logonLink", data_dialog_title = "Identification" })</li>
    </ul>
}

Backup/MvcLearningApp/Views/Shared/_Pager.cshtml
@model MvcLearningApp.Models.PagerView

@if (Model.Records > 0)
{
    <ol class="pagination">
            @if (Model.PagerPages > 1)
            {
                if (Model.CurrentPage != 1)
                {
                    <li style="display :inline-block;"><a class="btn-page_nav left" data-page="@(Model.CurrentPage - 1)" href="#">&#171;</a></li>
                }
                else
                {
                    <li style="display :inline-block;"><a class="btn-page_nav left">&#171;</a></li>
                }

                for (int i = 0; i < Model.PagerPages; i++)
                {

                    if (i + Model.StartPage == Model.CurrentPage)
                    {
                        <li style="display :inline-block;"><a class="btn-page active">@(i + Model.StartPage)</a></li>
                    }
                    else
                    {
                        <li style="display :inline-block;"><a class="btn-page" data-page="@(i + Model.StartPage)" href="?page=@(i + Model.StartPage)">@(i + Model.StartPage)</a></li>
                    }
                }

                if (Model.CurrentPage != Model.Pages)
                {
                    <li style="display :inline-block;"><a class="btn-page_nav right" data-page="@(Model.CurrentPage + 1)" href="#">&#187;</a></li>
                }
                else
                {
                    <li style="display :inline-block;"><a class="btn-page_nav right">&#187;</a></li>
                }
                <li style="display :inline-block;"><label>Pagina @Model.CurrentPage din @Model.Pages . Total: @Model.Records</label></li>
            }
    </ol>
}